### ISSUE TITLE
Conditionalization in portable-threads.lisp breaks it for future version of LispWorks

### ISSUE THREAD

**Issue by Yehouda** [binghe/portable-threads#1]
In LispWorks Ltd we test 8.0, and portable-threads doesn't load because the conditionalization in portable-threads.lisp.
The onditionalization 
      #+(or lispworks6 lispworks7)  
should be changed to:
    #-(or lispworks3 lispworks4 lispworks5)
and then it will work in all future versions.

**Comment by binghe** [comment]
Hi,

thanks for the news of ongoing LW 8.0 and this issue.

The changes literal in your way doesn't work everywhere, as `#-(or lispworks3 lispworks4 lispworks5)` will be also triggered in non-LispWorks platforms.  After some thoughts, I decided to add `:lispworks6+` into `*features*` (if ASDF is not loaded yet) and change all `(or lispworks6 lispwork7)` to `lispworks6+`.

The commit fcb1a3d2ff9f7d207b213785802f1fe5f202de6b is based on the above idea, let me know if it still doesn't work, or there's anything new in LW 8.0 that I should be aware of.

--Chun
